nodes:
  - host: "node1.example.com"
    user: "root"
    password: "your_password"
    port: 3306
    haproxy_server: "node1"
  - host: "node2.example.com"
    user: "root"
    password: "your_password"
    port: 3306
    haproxy_server: "node2"
  - host: "node3.example.com"
    user: "root"
    password: "your_password"
    port: 3306
    haproxy_server: "node3"

mysql:
  host: "172.19.1.190"
  port: 3306
  user: "root"
  password: "your_password_here"
  database: "information_schema"

haproxy:
  host: "haproxy.example.com"
  stats_port: port_number
  stats_path: "/stats;csv"
  stats_user: "admin"
  stats_password: "your_password"
  backend_name: "galera_cluster_backend"

telegram:
  enabled: false
  bot_token: "123456789:ABCDEF_your_bot_token_here"
  chat_id: "-1001122334455"  # channel/group/user ID

alerts:
  enabled: true
  cooldown_seconds: 300  # avoid alert flooding
  node:
    offline: true  # alert if node unsynced/not primary/error
  flow_control:
    active: true           # alert if active == true
    paused_threshold: 0.05 # alert if wsrep_flow_control_paused >= this
  qps:
    min: null              # set to a number to enable
    max: null
  wps:
    min: null
    max: null
  haproxy:
    connections_critical: null  # set to e.g. 500